name: GrupLAC Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install axios cheerio iconv-lite

      - name: Run scraper
        run: node scraper.js

      - name: Guardar cambios a la fuerza
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Añadimos el archivo generado
          git add investigadores.json
          
          # Hacemos el commit
          git commit -m "Datos actualizados: Limpieza de caracteres" || exit 0
          
          # FORZAMOS la subida para ignorar errores de 'fetch first' o 'rebase'
          git push origin main --force
